### ISSUE TITLE
Docker Image Source?

### ISSUE THREAD

**Issue by DeviantEng** [snibox/snibox-docker#1]
Would you be willing to provide your Makefiles, at least for the `nginx-puma` image?  I'm trying to deploy snibox to my Docker Swarm, and want to run it behind my external reverse proxy, but I believe the nginx settings in the `nginx-puma` instance are preventing it from working properly behind my reverse proxy.

I believe the problem is where you set `proxy_redirect  off` in the nginx default.conf on `nginx-puma`. 

Any advice would be appreciated.

**Comment by vavgustov** [comment]
it's available here: https://github.com/snibox/docker-images

**Comment by DeviantEng** [comment]
@vavgustov Oh wow, not sure how I missed that.  Thanks!
